/*
 * Copyright (c) 2003 Bilibili
 * Copyright (c) 2003 Fabrice Bellard
 * Copyright (c) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * This file is part of ijkPlayer.
 * Based on libavformat/allformats.c
 *
 * FFmpeg is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * FFmpeg is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with FFmpeg; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

#include "libavformat/avformat.h"
#include "libavformat/version.h"

/*
 * FFmpeg 7 migration note:
 *
 * FFmpeg 5.0 removed runtime registration of demuxers/protocols
 * (av_register_all / av_register_input_format / ffurl_register_protocol and the
 * mutable linked-list registry). The protocol and demuxer tables are now static
 * const arrays generated by configure, so ijkplayer's custom modules
 * (ijkio / ijkhttphook / ijktcphook / ijklongurl / ijksegment /
 * ijkmediadatasource protocols, ijklivehook demuxer) can no longer be injected
 * at runtime.
 *
 * These custom modules are IO enhancements (caching, app IO-event hooks, long
 * URL handling) layered on top of FFmpeg's native protocols. Basic playback —
 * including HLS, http(s)/tls and local files — is fully served by FFmpeg's
 * built-in http/https/tls/crypto/hls/file protocols, so we no-op the custom
 * registration here to run on FFmpeg 7.
 *
 * To restore the custom modules they must be compiled into libavformat and
 * added to the build-time protocol/demuxer lists (libavformat/protocol_list.c /
 * demuxer_list.c) instead of registered at runtime — tracked as follow-up work.
 */
void ijkav_register_all(void)
{
    static int initialized;

    if (initialized)
        return;
    initialized = 1;

    av_log(NULL, AV_LOG_INFO,
           "ijkav_register_all: custom ijk protocols/demuxers are disabled under "
           "FFmpeg 7 (runtime registration was removed); using native protocols\n");
}
